// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzoddyvygyumiarigfna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6b2RkeXZ5Z3l1bWlhcmlnZm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Mzg2NjgsImV4cCI6MjA2ODMxNDY2OH0.plWoZkDTY--lN2Mb5ISgtNvsn_Oxwlj0jwtGlhjsric";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});